language: go
go:
  - 1.4
  - 1.5
  - tip

install:
  - go get code.google.com/p/go-uuid/uuid
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/onsi/gomega
  - go get github.com/onsi/ginkgo/ginkgo
  - go install github.com/onsi/ginkgo/ginkgo
  - export PATH=$PATH:$HOME/gopath/bin

script: $HOME/gopath/bin/ginkgo -r --randomizeAllSpecs --randomizeSuites --race --trace
